name: ci build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  ubuntu-cmake:
    name: ubuntu
    runs-on: ubuntu-latest

    steps:
    - name: setup
      run: |
       sudo apt-get update
       sudo apt-get install cmake g++ libgtest-dev make libssl-dev
       sudo apt-get install redis valgrind
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make tutorial
      run: make tutorial
      
  fedora-cmake:
    name: fedora
    runs-on: ubuntu-latest
    container:
      image: fedora:latest

    steps:
    - uses: actions/checkout@v3
    - run: cat /etc/os-release
    - name: install dependencies
      run: |
       dnf -y update
       dnf -y install cmake gcc-c++ gtest-devel make
       dnf -y install openssl-devel redis valgrind
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make tutorial
      run: make tutorial

  freebsd-cmake:
    name: freebsd
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build and test on FreeBSD
      uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        mem: 2048
        copyback: false
        prepare: |
          pkg update -f
          pkg install -y cmake gmake gcc pkgconf openssl
        run: |
          freebsd-version
          gmake
          gmake tutorial
          cd tutorial
          ./parallel_wget http://github.com/
